
files: 'runpandas\/'
repos:
-   repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language: python_venv



