
files: 'runpandas\/'
repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.8
        args: [-t, py38]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3.8


