
files: 'runpandas\/'
repos:
-   repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
    -   id: black
        language_version: python3.8
        entry: black --version
-   repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        entry: flake8 --version
        language_version: python3.8